# Generated by Django 3.2.25 on 2025-12-31 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
            ],
            options={
                'verbose_name': '电影分类',
                'verbose_name_plural': '电影分类',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='电影标题')),
                ('description', models.TextField(verbose_name='电影描述')),
                ('director', models.CharField(max_length=100, verbose_name='导演')),
                ('actors', models.TextField(verbose_name='主演')),
                ('release_date', models.DateField(verbose_name='上映日期')),
                ('duration', models.IntegerField(verbose_name='时长(分钟)')),
                ('rating', models.FloatField(default=0, verbose_name='评分')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movie_posters/', verbose_name='海报')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examProject.category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '电影信息',
                'verbose_name_plural': '电影信息',
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_text', models.TextField(verbose_name='分享内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='分享时间')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examProject.movie', verbose_name='电影')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户分享',
                'verbose_name_plural': '用户分享',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('rating', models.IntegerField(default=5, verbose_name='评分(1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examProject.movie', verbose_name='电影')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '电影评论',
                'verbose_name_plural': '电影评论',
            },
        ),
        migrations.CreateModel(
            name='UserCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examProject.movie', verbose_name='电影')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏',
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
